spring.application.name=minebank-api

spring.datasource.url=jdbc:postgresql://localhost:5432/minebank
spring.datasource.username=minebank
spring.datasource.password=minebank

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true